export const theme = {
  colors: {
    background: "#fbf3e7",
    backgroundAlt: "#f6eadb",
    surface: "#ffffff",
    surfaceWarm: "#fff9f1",
    border: "#ead9c4",
    borderStrong: "#d9b996",
    text: "#241813",
    textMuted: "#6f5a4d",
    coffee: "#4b2e24",
    espresso: "#211511",
    caramel: "#b9783f",
    cream: "#fff3df",
    flamingo: "#e86f7d",
    flamingoDark: "#bf4c5d",
    sage: "#0f766e",
    sageSoft: "#e5f2ec",
    danger: "#9f3528",
    dangerSoft: "#fff1ed",
    disabled: "#a89a8d",
    adminBackground: "#eef3f1",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
  },
  radius: {
    sm: 6,
    md: 8,
    card: 8,
  },
  typography: {
    eyebrow: 12,
    body: 15,
    bodyLarge: 16,
    title: 22,
    hero: 34,
  },
  shadows: {
    card: {
      shadowColor: "#211511",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.09,
      shadowRadius: 14,
      elevation: 3,
    },
    soft: {
      shadowColor: "#211511",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.07,
      shadowRadius: 9,
      elevation: 2,
    },
  },
} as const;
